[package]
name = "leanpub-client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.23"
serde_json = "1.0.142"
tokio = { version = "1.47.1", features = ["macros"] }
clap = { version = "4.5.20", features = ["derive"] }
anyhow = "1.0.89"
dotenvy = "0.15.7"
